# Mixtile custom Yocto layer
BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "mixtile"
BBFILE_PATTERN_mixtile = "^${LAYERDIR}/"
BBFILE_PRIORITY_mixtile = "9"

LAYERSERIES_COMPAT_mixtile = "scarthgap"
